events { worker_connections 512; }

http {
    proxy_cache_path /var/cache/nginx levels=1:2 keys_zone=david_zone:5m max_size=500m;

    upstream nodes-david {
        server david-node-1:80;
        server david-node-2:80;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://nodes-david;
            proxy_cache david_zone;
            proxy_cache_valid 200 5m;
            add_header X-David-Cache $upstream_cache_status;
        }
    }
}